module.exports = {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "type-enum": [
      2,
      "always",
      [
        "build",
        "ci",
        "chore",
        "docs",
        "feat",
        "fix",
        "perf",
        "refactor",
        "revert",
        "style",
        "test",
      ],
    ],
    "scope-enum": [
      1,
      "always",
      [
        "frontend",
        "backend",
        "contracts",
        "ci",
        "k8s",
        "deps",
        "docs",
        "release",
        "hooks",
        "security",
        "sla",
        "chaos",
        "auth",
        "escrow",
        "dispute",
        "profile",
        "ratings",
        "config",
      ],
    ],
  },
};
