/**
 * Re-exports all domain types from the shared @marketpay/types package.
 *
 * This file preserves backwards compatibility for existing imports
 * (e.g. `import { Job } from "@/utils/types"`). New code should import
 * directly from `@marketpay/types`.
 */

export {
  type JobStatus,
  type UserRole,
  type Currency,
  type JobVisibility,
  type FreelancerTier,
  type AvailabilityStatus,
  type PortfolioItemType,
  type ReferralStatus,
  type ApplicationStatus,
  type NotificationType,
  type TimeInvoiceStatus,
  type BridgeChain,
  type BridgeTransferStatus,
  type PortfolioItem,
  type Availability,
  type JobMilestone,
  type NotificationItem,
  type Job,
  type ClientReputation,
  type Application,
  type UserProfile,
  type ProfileStats,
  type ResponseTime,
  type Rating,
  type ProposalTemplate,
  type PriceAlertPreference,
  type ClientSpendingFreelancer,
  type ClientSpendingAnalytics,
  type EscrowState,
  type Message,
  type PortfolioFile,
  type TokenInfo,
  type TokenBalance,
  type SkillEndorsement,
  type SkillBadge,
  type AssessmentQuestion,
  type ReferralReferee,
  type ReferralPayout,
  type ReferralStats,
  type ReferralTreeNode,
  type TimeEntry,
  type TimeInvoice,
  type JobCompletionPrediction,
  type JobAnalytics,
  type BulkActionResponse,
  type JobInvitation,
  type BridgeTransfer,
} from "@marketpay/types";
